Oauth
Matt-Gleich/fgh pull request #4
Opened 2020-10-24 01:29 UTC by cjdenio

## Description

Three cheers for OAuth! :tada: 

## Steps

- [x] My change requires a change to the documentation
- [ ] I have updated the accessible documentation according
- [x] I have read the **CONTRIBUTING.md** file
- [x] There is no duplicate open or closed pull request for this fix/addition/issue resolution.

## Original Issue

This PR resolves #2

2020-10-24 02:30 UTC, Matt-Gleich requested changes
2 small suggestions but besides that, I think we are good to merge! Really great job on this. The code is super clear, organized, and well documented. Thank you so much!!

2020-10-24 02:30 UTC, Matt-Gleich commented on README.md
> +Before using `fgh`, you'll need to give it access to your GitHub account. Simply run `fgh login` to quickly get set up!
Could we add a note saying that users could use a PAT if they can't get OAuth access (organizations permissions for example)? Is it a good idea to point out where the token is stored on a user's machine?

2020-10-24 02:30 UTC, Matt-Gleich commented on pkg/commands/login/exchange.go
> +func Exchange(code string) (string, error) {
Please add godoc to all functions you created

2020-10-25 17:15 UTC, Matt-Gleich approved these changes
Looks good to me!

2020-10-25 17:15 UTC, Matt-Gleich commented
Thanks again @cjdenio!!

2020-10-25 17:19 UTC, merged

2020-10-25 17:19 UTC, cjdenio commented
No problem! Glad to help!